### PR TITLE
Some corrections for D7.1 report

### PR DESCRIPTION
**Pull request by alex-konovalov**
@dimpase @nthiery please have a look.

### CODE REVIEW

**Comment by alex-konovalov** [comment]
@dimpase I've also left two questions in the text under `%TODO`

**Comment by alex-konovalov** [comment]
@dimpase however, that's is some statistical data, while the text about good evidence seems to be a little bit subjective...

**Comment by dimpase** [comment]
@alex-konovalov my text says that there is a dozen  BSD clones and no Linux clones. This is hard to deny.

**Comment by alex-konovalov** [comment]
@dimpase How do you count dozen? https://www.freebsd.org/doc/en_US.ISO8859-1/articles/explaining-bsd/comparing-bsd-and-linux.html has FreeBSD, NetBSD, OpenBSD and DragonFlyBSD. What else? Also, what do you mean by clone? For example, https://en.wikipedia.org/wiki/Linux_kernel#Variants says "There are certain variants of the Linux kernel that provide additional functionality, but do not belong to the Linux kernel mainline. Such variants of the Linux kernel include Linux-libre, Compute Node Linux, Cooperative Linux, Longene, grsecurity, INK, L4Linux, MkLinux, RTLinux, and User-mode Linux. Some of these variants have been partially merged into the mainline" - aren't those clones?

**Comment by dimpase** [comment]
FreeBSD, NetBSD, OpenBSD, DragonFlyBSD, Darwin, OSX, iOS, SunOS, Ultrix, OSF/1, JunOS, GhostBSD, ClosedBSD, Bitrig are all forks of 4.4BSD or some predecessor, or of each other...

If on the other hand you check what Linux-libre is, they use the standard Linux kernel. Compute Node Linux is a port of Linux kernel to Crays (i.e. not a fork either). Cooperative linux (coLinux) was a virtual machine-like build of a standard linux kernel. Etc. etc. No forks, sorry...

**Comment by dimpase** [comment]
see current https://gitter.im/OpenDreamKit

**Pull request merged**
