### PR TITLE
Replace Hans-Petter Langtangen with myself as PI for simula

### PR DESCRIPTION
**Pull request by martinal**
Also increased PM count a little.

### CODE REVIEW

**Comment by JohnCremona** [comment]
Surely the number of person months is hard-wired into our contract, since it translates into the amount of funding?

**Comment by martinal** [comment]
The funding remains unchanged. I'm less senior and less expensive than Langtangen. Benoit asked for the PM to be updated.

**Comment by JohnCremona** [comment]
Thanks for the explanation.

**Comment by bpilorget** [comment]
Thanks Martin. Yes the funding remains the same but if the salary costs per hour decrease, it automatically allows more Person-Months. That's the case for Simula.
But such an evolution doesn't require an amendment because as you said John the funding remains the same, we are simply doing this because we have the chance to do it with the addition of Erlangen-Nürnberg.

**Pull request merged**
