### PR TITLE
Glossary: add SGE and reduce margins to fits on one page

### PR DESCRIPTION
**Pull request by willfurnass**

### CODE REVIEW

**Comment by videlec** [comment]
Please, don't touch the .tex file that is automatically generated. Update read_and_write.py

**Comment by pdehaye** [comment]
don't commit the tex file...

**Comment by videlec** [comment]
@pdehaye : I already mentioned this fact

I will provide a commit in a second for including SGE

**Comment by pdehaye** [comment]
but it's not in .gitignore
paul

**Comment by videlec** [comment]
done in 3cf32b7

**Pull request closed without merging**
