### PR TITLE
Add a Gitter chat badge to README.rst

### PR DESCRIPTION
**Pull request by gitter-badger**
### OpenDreamKit/OpenDreamKit now has a Chat Room on Gitter

@defeo has just created a chat room. You can visit it here: [https://gitter.im/OpenDreamKit/OpenDreamKit](https://gitter.im/OpenDreamKit/OpenDreamKit?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.rst:

[Gitter](https://gitter.im/OpenDreamKit/OpenDreamKit?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by alex-konovalov** [comment]
Are we happy to accept this automated pull request?

**Comment by nthiery** [comment]
On Wed, Sep 09, 2015 at 05:37:43AM -0700, Alexander Konovalov wrote:
>    Are we happy to accept this automated pull request?

Fine with me.
				Nicolas
--
Nicolas M. Thiéry "Isil" <nthiery@users.sf.net>
http://Nicolas.Thiery.name/

**Comment by defeo** [comment]
Hmmm, no, sorry. This was my mistake, the pull request should not be merged. I forgot to close this.

**Comment by defeo** [comment]
I just added the correct badge to the Readme

**Pull request closed without merging**
