### PR TITLE
Suggested changes to WP7: move JOOMMF evaluation into WP2 task

### PR DESCRIPTION
**Pull request by fangohr**
- move all XFEL time from WP7 to WP2 (with the one task associated)
- merge deliverable from WP7 with the one in WP2 (to also reduce the number of deliverables)
- updated grant history to reflect this

@nthiery, @bpilorget - do you want to review and feedback / merge?

[Thanks @mb1a15 for putting this together.]

### CODE REVIEW

**Comment by kohlhase** [comment]
what is the state of this merge request, did the changes ever make it into the trunk?

**Comment by fangohr** [comment]
Hm, good question. These are the changes we made for the grant agreement (which has been approved), so I presumed they have been merged. But it looks like that still needs doing? @nthiery @bpilorget

**Comment by nthiery** [comment]
These changes are not for the previous grant agreement ammendment, but for the work plan revisions (and tentatively a future grant agreement ammendment). Hence we still confirmation by the reviewers.

**Comment by nthiery** [comment]
Our project officer said the reviewers are essentially ok with the changes. She asked for updating our document w.r.t. the changes and send the new version to her for final check.
I am thus merging in this PR. Thanks for preparing it!

Just one thing: removing/commenting out deliverables has the annoying effect of inducing a renumbering of other deliverables; and prevents refering to it in this or other documents. Do you mind just briefly updating the sources (directly on master) to not comment out cancelled deliverables, but rather adding CANCELLED in their title? We will later figure out better latex support for this with Michael.
Thanks!

**Pull request merged**
