### PR TITLE
Correct descriptions of deliverables for UK

### PR DESCRIPTION
**Pull request by wbhart**
Nicolas, I was unable to find the history file you were referring to, so I've just added descriptions of each change to the tickets.

### CODE REVIEW

**Comment by nthiery** [comment]
On Tue, Dec 06, 2016 at 03:14:58AM -0800, wbhart wrote:
>    Nicolas, I was unable to find the history file you were referring to,

<OpenDreamKit>/Proposal/grantagreement-history.tex

Anyway, it's good to also have comments on the changes, possibly
longer, on the tickets as well.

Cheers,

**Comment by wbhart** [comment]
Thanks. Do you want me to make changes to that file now? Or are you happy to do that?

**Comment by wbhart** [comment]
Was there any response from our project officer?

**Comment by kohlhase** [comment]
what is the state of this merge request, did the changes ever make it into the trunk?

**Comment by nthiery** [comment]
I believe all changes suggested here have been implemented in the file. Closing this pull request.

**Pull request closed without merging**
